### ISSUE TITLE
Moving efforts to support community provider

### ISSUE THREAD

**Issue by jeqo** [sysco-middleware/terraform-provider-kafka-old#12]
After releasing the initial release of Kafka provider, we have found this project listed by Terraform as community connector for Kafka: https://github.com/Mongey/terraform-provider-kafka

We found it very similar to our implementation but more complete, including:
* ACL
* SSL support for secure connections

We have made an initial fork and fix some of the issues on that repository already, but I want to gather some feedback/opinions before moving our efforts on supporting that repository regarding Kafka and Terraform.

The same user also has https://github.com/Mongey/terraform-provider-kafka-connect that can be used for deploying Kafka Connectors to a distributed cluster. We are using it for one of our customers already.

**Comment by jeqo** [comment]
CC @PrakharSrivastav

**Comment by PrakharSrivastav** [comment]
@jeqo  I have tested https://github.com/Mongey/terraform-provider-kafka and it covers all the features that we are trying to implement. However, it supports version Kafka 1 only.

I propose to fork this repo and add support for Kafka version 2 as well.

**Comment by jeqo** [comment]
@PrakharSrivastav thanks for your feedback! Renaming with suffix `-old` and forking community provider
